### ISSUE TITLE
cross-env included as a dev and production dependency with conflicting versions ...

### ISSUE THREAD

**Issue by dph01** [vuejsdevelopers/vuejs-calendar#3]
When trying to get started with the calendar project, I ran `npm run start` for the first time and got the error:
 
    ERROR in ./~/css-loader!./~/sass-loader!./src/style.scss
    Module build failed: Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (57)

After a bit of digging around I noticed that in Package.json I had ..

```
"dependencies": {
     ....
    "cross-env": "~3.1.3",

"devDependencies": {
    ....
    "cross-env": "~3.0.0",
```

Removing the dev dependency lead to sass-load problem being resolved.

**Comment by anthonygore** [comment]
You're right about the redundant dev dependency. I'd be surprised if that's the cause of the node-sass issue but maybe it is!
